import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Invoice } from '@/types';

export function exportInvoiceToPDF(invoice: Invoice): void {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(24);
  doc.setTextColor(99, 102, 241); // Primary color
  doc.text('ARPAY', 20, 25);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Financial Management System', 20, 32);
  
  // Invoice Title
  doc.setFontSize(18);
  doc.setTextColor(0, 0, 0);
  doc.text('INVOICE', 150, 25);
  
  // Invoice Details Box
  doc.setDrawColor(200, 200, 200);
  doc.setFillColor(249, 250, 251);
  doc.roundedRect(130, 30, 60, 30, 3, 3, 'F');
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Invoice ID:', 135, 40);
  doc.text('Date:', 135, 48);
  doc.text('Due Date:', 135, 56);
  
  doc.setTextColor(0, 0, 0);
  doc.text(invoice.id, 160, 40);
  doc.text(invoice.date, 160, 48);
  doc.text(invoice.dueDate, 160, 56);
  
  // Client Info
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text('Bill To:', 20, 50);
  
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text(invoice.clientName, 20, 58);
  
  // Invoice Type Badge
  const typeColors: Record<string, [number, number, number]> = {
    Project: [59, 130, 246],
    Customer: [139, 92, 246],
    Expense: [249, 115, 22],
  };
  const color = typeColors[invoice.invoiceType] || [100, 100, 100];
  doc.setFillColor(color[0], color[1], color[2]);
  doc.roundedRect(20, 65, 30, 8, 2, 2, 'F');
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text(invoice.invoiceType, 25, 70);
  
  // Status Badge
  const statusColors: Record<string, [number, number, number]> = {
    Paid: [34, 197, 94],
    Pending: [245, 158, 11],
    Overdue: [239, 68, 68],
  };
  const statusColor = statusColors[invoice.status] || [100, 100, 100];
  doc.setFillColor(statusColor[0], statusColor[1], statusColor[2]);
  doc.roundedRect(55, 65, 25, 8, 2, 2, 'F');
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text(invoice.status, 60, 70);
  
  // Line Items Table
  const tableData = invoice.lineItems.map((item, index) => [
    (index + 1).toString(),
    item.description || 'Item',
    item.quantity.toString(),
    `₹${item.price.toLocaleString('en-IN')}`,
    `₹${(item.quantity * item.price).toLocaleString('en-IN')}`,
  ]);
  
  autoTable(doc, {
    startY: 85,
    head: [['#', 'Description', 'Qty', 'Price', 'Total']],
    body: tableData,
    theme: 'striped',
    headStyles: {
      fillColor: [99, 102, 241],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
    },
    styles: {
      fontSize: 10,
      cellPadding: 5,
    },
    columnStyles: {
      0: { cellWidth: 15 },
      1: { cellWidth: 80 },
      2: { cellWidth: 20, halign: 'center' },
      3: { cellWidth: 35, halign: 'right' },
      4: { cellWidth: 35, halign: 'right' },
    },
  });
  
  // Total Section
  const finalY = (doc as any).lastAutoTable.finalY || 120;
  
  doc.setDrawColor(200, 200, 200);
  doc.line(120, finalY + 10, 190, finalY + 10);
  
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text('Subtotal:', 125, finalY + 20);
  doc.text('Tax (0%):', 125, finalY + 28);
  
  doc.setTextColor(0, 0, 0);
  doc.text(`₹${invoice.amount.toLocaleString('en-IN')}`, 170, finalY + 20, { align: 'right' });
  doc.text('₹0', 170, finalY + 28, { align: 'right' });
  
  doc.setDrawColor(99, 102, 241);
  doc.setLineWidth(0.5);
  doc.line(120, finalY + 32, 190, finalY + 32);
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Total:', 125, finalY + 42);
  doc.setTextColor(99, 102, 241);
  doc.text(`₹${invoice.amount.toLocaleString('en-IN')}`, 190, finalY + 42, { align: 'right' });
  
  // Footer
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text('Thank you for your business!', 105, 280, { align: 'center' });
  doc.text('Generated by ARPAY - Financial Management System', 105, 286, { align: 'center' });
  
  // Save the PDF
  doc.save(`invoice-${invoice.id}.pdf`);
}
